<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // ── Projects ──────────────────────────────────────────────────────────
        $projects = [

            // 1) مشروع مناقَش ومؤرشف (2022-2023)
            [
                'project_idea_id'     => 5,
                'department_id'       => 2,
                'semester_id'         => 2,
                'supervisor_id'       => 5,
                'co_supervisor_id'    => null,
                'created_by'          => 5,
                'approved_by'         => 1,
                'project_number'      => 'GRAD-2023-0001',
                'title_ar'            => 'نظام إدارة المستشفيات الإلكتروني',
                'title_en'            => 'Electronic Hospital Management System',
                'description_ar'      => 'منصة شاملة لإدارة العمليات اليومية في المستشفيات تشمل تسجيل المرضى وجدولة المواعيد وإدارة الطواقم الطبية.',
                'description_en'      => null,
                'objectives_ar'       => "رقمنة العمليات الإدارية للمستشفى\nتحسين تجربة المريض\nتوفير تقارير إدارية شاملة",
                'objectives_en'       => null,
                'expected_outcomes_ar'=> null,
                'expected_outcomes_en'=> null,
                'methodology_ar'      => null,
                'methodology_en'      => null,
                'project_type'        => 'graduation',
                'academic_year_level' => 4,
                'tools'               => json_encode(['Laravel', 'Vue.js', 'MySQL', 'Pusher']),
                'technologies'        => json_encode(['REST API', 'WebSockets']),
                'registration_date'   => '2023-02-05',
                'start_date'          => '2023-02-10',
                'expected_end_date'   => '2023-06-01',
                'submission_date'     => '2023-05-28',
                'defense_date'        => '2023-06-10',
                'actual_defense_date' => '2023-06-10',
                'defense_time'        => '10:00:00',
                'defense_location'    => 'كلية الحاسبات',
                'defense_room'        => 'قاعة 3أ',
                'status'              => 'archived',
                'approved_at'         => '2023-02-08',
                'rejection_reason'    => null,
                'is_discussed'        => true,
                'discussed_at'        => '2023-06-10 10:00:00',
                'final_grade'         => 91.5,
                'grade_letter'        => 'A',
                'committee_notes_ar'  => 'مشروع متميز يعكس مستوى عالٍ من الفهم والتطبيق.',
                'committee_notes_en'  => null,
                'is_archived'         => true,
                'archived_at'         => '2023-07-01',
                'archive_notes'       => null,
                'supervisor_notes'    => 'الطلاب أبدوا التزاماً ممتازاً طوال فترة المشروع',
                'progress_percentage' => 100,
                'created_at'          => $now,
                'updated_at'          => $now,
                'deleted_at'          => null,
            ],

            // 2) مشروع مناقَش (2023-2024)
            [
                'project_idea_id'     => 2,
                'department_id'       => 1,
                'semester_id'         => 4,
                'supervisor_id'       => 3,
                'co_supervisor_id'    => null,
                'created_by'          => 3,
                'approved_by'         => 1,
                'project_number'      => 'GRAD-2024-0001',
                'title_ar'            => 'تطبيق تتبع الحضور الجامعي باستخدام التعرف على الوجه',
                'title_en'            => 'University Attendance Tracking with Facial Recognition',
                'description_ar'      => 'نظام ذكي لتسجيل حضور الطلاب تلقائياً عن طريق التعرف على الوجه.',
                'description_en'      => null,
                'objectives_ar'       => "أتمتة تسجيل الحضور والغياب\nتقليل التلاعب",
                'objectives_en'       => null,
                'expected_outcomes_ar'=> null,
                'expected_outcomes_en'=> null,
                'methodology_ar'      => 'استخدام نموذج DeepFace للتعرف على الوجوه',
                'methodology_en'      => null,
                'project_type'        => 'graduation',
                'academic_year_level' => 4,
                'tools'               => json_encode(['Python', 'OpenCV', 'TensorFlow', 'Django', 'MySQL']),
                'technologies'        => json_encode(['Deep Learning', 'CNN', 'REST API']),
                'registration_date'   => '2024-02-03',
                'start_date'          => '2024-02-10',
                'expected_end_date'   => '2024-06-01',
                'submission_date'     => '2024-05-25',
                'defense_date'        => '2024-06-08',
                'actual_defense_date' => '2024-06-08',
                'defense_time'        => '09:00:00',
                'defense_location'    => 'كلية الحاسبات وتقنية المعلومات',
                'defense_room'        => 'قاعة 101',
                'status'              => 'defended',
                'approved_at'         => '2024-02-07',
                'rejection_reason'    => null,
                'is_discussed'        => true,
                'discussed_at'        => '2024-06-08 09:00:00',
                'final_grade'         => 88.0,
                'grade_letter'        => 'B+',
                'committee_notes_ar'  => 'مشروع جيد جداً مع تطبيق ناجح للذكاء الاصطناعي.',
                'committee_notes_en'  => null,
                'is_archived'         => false,
                'archived_at'         => null,
                'archive_notes'       => null,
                'supervisor_notes'    => 'الفريق أبدى جهداً كبيراً في التحسين المستمر للدقة',
                'progress_percentage' => 100,
                'created_at'          => $now,
                'updated_at'          => $now,
                'deleted_at'          => null,
            ],

            // 3) مشروع قيد التنفيذ (الفصل الحالي)
            [
                'project_idea_id'     => 1,
                'department_id'       => 1,
                'semester_id'         => 6,
                'supervisor_id'       => 3,
                'co_supervisor_id'    => null,
                'created_by'          => 9,
                'approved_by'         => 1,
                'project_number'      => 'GRAD-2025-0001',
                'title_ar'            => 'نظام إدارة مشاريع التخرج الذكي للجامعات',
                'title_en'            => 'Smart Graduation Project Management System for Universities',
                'description_ar'      => 'تطوير منصة إلكترونية متكاملة لإدارة مشاريع التخرج في الجامعات.',
                'description_en'      => 'Developing a comprehensive electronic platform for managing graduation projects.',
                'objectives_ar'       => "تنظيم عملية إدارة مشاريع التخرج\nتسهيل التواصل بين الطلاب والمشرفين",
                'objectives_en'       => null,
                'expected_outcomes_ar'=> "منصة ويب متكاملة باللغتين\nنظام صلاحيات متعدد الأدوار",
                'expected_outcomes_en'=> null,
                'methodology_ar'      => 'منهجية Agile مع دورات تطوير أسبوعية',
                'methodology_en'      => null,
                'project_type'        => 'graduation',
                'academic_year_level' => 4,
                'tools'               => json_encode(['Laravel 12', 'MySQL', 'Bootstrap 5', 'JavaScript']),
                'technologies'        => json_encode(['PHP 8.3', 'Blade Templates', 'Eloquent ORM']),
                'registration_date'   => '2025-02-05',
                'start_date'          => '2025-02-10',
                'expected_end_date'   => '2025-06-01',
                'submission_date'     => null,
                'defense_date'        => '2025-06-12',
                'actual_defense_date' => null,
                'defense_time'        => '11:00:00',
                'defense_location'    => 'كلية الحاسبات وتقنية المعلومات',
                'defense_room'        => 'قاعة المناقشات A',
                'status'              => 'in_progress',
                'approved_at'         => '2025-02-08',
                'rejection_reason'    => null,
                'is_discussed'        => false,
                'discussed_at'        => null,
                'final_grade'         => null,
                'grade_letter'        => null,
                'committee_notes_ar'  => null,
                'committee_notes_en'  => null,
                'is_archived'         => false,
                'archived_at'         => null,
                'archive_notes'       => null,
                'supervisor_notes'    => 'الفريق يسير بشكل ممتاز. يُطلب تسريع العمل على وحدة التقارير.',
                'progress_percentage' => 75,
                'created_at'          => $now,
                'updated_at'          => $now,
                'deleted_at'          => null,
            ],

            // 4) مشروع معلق في انتظار الاعتماد
            [
                'project_idea_id'     => null,
                'department_id'       => 4,
                'semester_id'         => 6,
                'supervisor_id'       => 4,
                'co_supervisor_id'    => null,
                'created_by'          => 12,
                'approved_by'         => null,
                'project_number'      => 'GRAD-2025-0002',
                'title_ar'            => 'نظام توصية المقررات الدراسية باستخدام الذكاء الاصطناعي',
                'title_en'            => 'AI-based Course Recommendation System',
                'description_ar'      => 'تطوير نظام ذكي يوصي الطلاب بالمقررات الدراسية المناسبة.',
                'description_en'      => null,
                'objectives_ar'       => "تقديم توصيات مخصصة\nتحسين مسيرة الطالب الأكاديمية",
                'objectives_en'       => null,
                'expected_outcomes_ar'=> "نموذج توصية دقيق\nواجهة مستخدم سهلة",
                'expected_outcomes_en'=> null,
                'methodology_ar'      => null,
                'methodology_en'      => null,
                'project_type'        => 'graduation',
                'academic_year_level' => 4,
                'tools'               => json_encode(['Python', 'Flask', 'Scikit-learn', 'React']),
                'technologies'        => json_encode(['Collaborative Filtering', 'Hybrid Recommender']),
                'registration_date'   => '2025-02-10',
                'start_date'          => null,
                'expected_end_date'   => '2025-06-01',
                'submission_date'     => null,
                'defense_date'        => null,
                'actual_defense_date' => null,
                'defense_time'        => null,
                'defense_location'    => null,
                'defense_room'        => null,
                'status'              => 'pending',
                'approved_at'         => null,
                'rejection_reason'    => null,
                'is_discussed'        => false,
                'discussed_at'        => null,
                'final_grade'         => null,
                'grade_letter'        => null,
                'committee_notes_ar'  => null,
                'committee_notes_en'  => null,
                'is_archived'         => false,
                'archived_at'         => null,
                'archive_notes'       => null,
                'supervisor_notes'    => null,
                'progress_percentage' => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
                'deleted_at'          => null,
            ],

            // 5) مشروع فصلي قيد التنفيذ
            [
                'project_idea_id'     => 9,
                'department_id'       => 2,
                'semester_id'         => 6,
                'supervisor_id'       => 5,
                'co_supervisor_id'    => null,
                'created_by'          => 14,
                'approved_by'         => 1,
                'project_number'      => 'SEM-2025-0001',
                'title_ar'            => 'نظام حجز مواعيد المرافق الجامعية',
                'title_en'            => 'University Facilities Booking System',
                'description_ar'      => 'نظام لحجز القاعات والملاعب والمعامل في الجامعة.',
                'description_en'      => null,
                'objectives_ar'       => "تسهيل حجز المرافق\nمنع تضارب الحجوزات",
                'objectives_en'       => null,
                'expected_outcomes_ar'=> null,
                'expected_outcomes_en'=> null,
                'methodology_ar'      => null,
                'methodology_en'      => null,
                'project_type'        => 'semester',
                'academic_year_level' => 3,
                'tools'               => json_encode(['Laravel', 'FullCalendar.js', 'MySQL', 'Bootstrap']),
                'technologies'        => json_encode(['REST API', 'AJAX']),
                'registration_date'   => '2025-02-08',
                'start_date'          => '2025-02-15',
                'expected_end_date'   => '2025-05-15',
                'submission_date'     => null,
                'defense_date'        => '2025-05-20',
                'actual_defense_date' => null,
                'defense_time'        => '14:00:00',
                'defense_location'    => null,
                'defense_room'        => null,
                'status'              => 'approved',
                'approved_at'         => '2025-02-10',
                'rejection_reason'    => null,
                'is_discussed'        => false,
                'discussed_at'        => null,
                'final_grade'         => null,
                'grade_letter'        => null,
                'committee_notes_ar'  => null,
                'committee_notes_en'  => null,
                'is_archived'         => false,
                'archived_at'         => null,
                'archive_notes'       => null,
                'supervisor_notes'    => null,
                'progress_percentage' => 55,
                'created_at'          => $now,
                'updated_at'          => $now,
                'deleted_at'          => null,
            ],

            // 6) مشروع AI مؤرشف من 2022-2023
            [
                'project_idea_id'     => null,
                'department_id'       => 4,
                'semester_id'         => 1,
                'supervisor_id'       => 4,
                'co_supervisor_id'    => null,
                'created_by'          => 4,
                'approved_by'         => 1,
                'project_number'      => 'GRAD-2022-0001',
                'title_ar'            => 'تصنيف المشاعر في التغريدات العربية',
                'title_en'            => 'Sentiment Analysis in Arabic Tweets',
                'description_ar'      => 'تطوير نموذج تعلم آلي لتحليل المشاعر في تغريدات اللغة العربية.',
                'description_en'      => null,
                'objectives_ar'       => "تصنيف المشاعر بدقة عالية\nمعالجة اللهجات العربية",
                'objectives_en'       => null,
                'expected_outcomes_ar'=> "نموذج بدقة أعلى من 85%\nمجموعة بيانات عربية",
                'expected_outcomes_en'=> null,
                'methodology_ar'      => null,
                'methodology_en'      => null,
                'project_type'        => 'graduation',
                'academic_year_level' => 4,
                'tools'               => json_encode(['Python', 'AraBERT', 'Transformers', 'FastAPI']),
                'technologies'        => json_encode(['BERT', 'Transfer Learning', 'Arabic NLP']),
                'registration_date'   => '2022-09-05',
                'start_date'          => '2022-09-10',
                'expected_end_date'   => '2023-01-10',
                'submission_date'     => '2023-01-05',
                'defense_date'        => '2023-01-15',
                'actual_defense_date' => '2023-01-15',
                'defense_time'        => '10:00:00',
                'defense_location'    => 'كلية الحاسبات',
                'defense_room'        => 'قاعة المناقشات ب',
                'status'              => 'archived',
                'approved_at'         => '2022-09-08',
                'rejection_reason'    => null,
                'is_discussed'        => true,
                'discussed_at'        => '2023-01-15 10:00:00',
                'final_grade'         => 95.0,
                'grade_letter'        => 'A+',
                'committee_notes_ar'  => 'مشروع استثنائي يرقى إلى مستوى الأبحاث الأكاديمية المنشورة.',
                'committee_notes_en'  => null,
                'is_archived'         => true,
                'archived_at'         => '2023-02-01',
                'archive_notes'       => 'مشروع متميز تم توصيته للنشر الأكاديمي',
                'supervisor_notes'    => null,
                'progress_percentage' => 100,
                'created_at'          => $now,
                'updated_at'          => $now,
                'deleted_at'          => null,
            ],
        ];

        DB::table('projects')->insert($projects);

        // ── Project Students ──────────────────────────────────────────────────
        DB::table('project_students')->insert([
            // project 1
            ['project_id'=>1,'student_id'=>9, 'role'=>'leader','joined_at'=>'2023-02-05','status'=>'active','individual_grade'=>92.0,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>1,'student_id'=>10,'role'=>'member','joined_at'=>'2023-02-05','status'=>'active','individual_grade'=>91.0,'created_at'=>$now,'updated_at'=>$now],
            // project 2
            ['project_id'=>2,'student_id'=>11,'role'=>'leader','joined_at'=>'2024-02-03','status'=>'active','individual_grade'=>88.0,'created_at'=>$now,'updated_at'=>$now],
            // project 3
            ['project_id'=>3,'student_id'=>9, 'role'=>'leader','joined_at'=>'2025-02-05','status'=>'active','individual_grade'=>null,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>3,'student_id'=>10,'role'=>'member','joined_at'=>'2025-02-05','status'=>'active','individual_grade'=>null,'created_at'=>$now,'updated_at'=>$now],
            // project 4
            ['project_id'=>4,'student_id'=>12,'role'=>'leader','joined_at'=>'2025-02-10','status'=>'active','individual_grade'=>null,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>4,'student_id'=>13,'role'=>'member','joined_at'=>'2025-02-10','status'=>'active','individual_grade'=>null,'created_at'=>$now,'updated_at'=>$now],
            // project 5
            ['project_id'=>5,'student_id'=>14,'role'=>'leader','joined_at'=>'2025-02-08','status'=>'active','individual_grade'=>null,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>5,'student_id'=>15,'role'=>'member','joined_at'=>'2025-02-08','status'=>'active','individual_grade'=>null,'created_at'=>$now,'updated_at'=>$now],
            // project 6
            ['project_id'=>6,'student_id'=>11,'role'=>'leader','joined_at'=>'2022-09-05','status'=>'active','individual_grade'=>95.0,'created_at'=>$now,'updated_at'=>$now],
        ]);

        // ── Milestones for project 3 ──────────────────────────────────────────
        DB::table('project_milestones')->insert([
            ['project_id'=>3,'title_ar'=>'تحليل المتطلبات وتصميم قاعدة البيانات','title_en'=>'Requirements Analysis & DB Design','due_date'=>'2025-02-28','completed_date'=>'2025-02-26','status'=>'completed',  'order'=>1,'weight_percentage'=>15,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>3,'title_ar'=>'تطوير الـ Backend وقاعدة البيانات',      'title_en'=>'Backend & Database Development',  'due_date'=>'2025-03-31','completed_date'=>'2025-03-28','status'=>'completed',  'order'=>2,'weight_percentage'=>25,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>3,'title_ar'=>'تطوير واجهة المستخدم (Frontend)',         'title_en'=>'Frontend Development',            'due_date'=>'2025-04-30','completed_date'=>null,        'status'=>'in_progress','order'=>3,'weight_percentage'=>25,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>3,'title_ar'=>'الاختبار والتحقق من الجودة',             'title_en'=>'Testing & Quality Assurance',      'due_date'=>'2025-05-20','completed_date'=>null,        'status'=>'pending',    'order'=>4,'weight_percentage'=>20,'created_at'=>$now,'updated_at'=>$now],
            ['project_id'=>3,'title_ar'=>'التوثيق والتقرير النهائي',                'title_en'=>'Documentation & Final Report',     'due_date'=>'2025-06-01','completed_date'=>null,        'status'=>'pending',    'order'=>5,'weight_percentage'=>15,'created_at'=>$now,'updated_at'=>$now],
        ]);

        // ── Reports for project 3 — جميع الأعمدة بشكل صريح ──────────────────
        DB::table('project_reports')->insert([
            [
                'project_id'          => 3,
                'submitted_by'        => 9,
                'title_ar'            => 'تقرير الأسبوع الأول - تحليل المتطلبات',
                'title_en'            => null,
                'content_ar'          => 'تم خلال هذا الأسبوع: مراجعة المتطلبات الوظيفية وغير الوظيفية، تصميم مخطط قاعدة البيانات الأولي.',
                'content_en'          => null,
                'report_type'         => 'weekly',
                'week_number'         => 1,
                'report_date'         => '2025-02-17',
                'status'              => 'approved',
                'supervisor_feedback' => 'عمل جيد. يرجى إضافة مخطط UML لعلاقات الكيانات في التقرير القادم.',
                'reviewed_by'         => 3,
                'reviewed_at'         => '2025-02-19 10:00:00',
                'grade'               => 88.0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'project_id'          => 3,
                'submitted_by'        => 9,
                'title_ar'            => 'تقرير الأسبوع الثاني - تصميم قاعدة البيانات',
                'title_en'            => null,
                'content_ar'          => 'تم خلال هذا الأسبوع: إنهاء تصميم قاعدة البيانات بالكامل (15 جدولاً)، إنشاء الـ Migrations، كتابة الـ Seeders الأساسية.',
                'content_en'          => null,
                'report_type'         => 'weekly',
                'week_number'         => 2,
                'report_date'         => '2025-02-24',
                'status'              => 'approved',
                'supervisor_feedback' => 'ممتاز. التصميم احترافي ومدروس جيداً.',
                'reviewed_by'         => 3,
                'reviewed_at'         => '2025-02-26 10:00:00',
                'grade'               => 92.0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'project_id'          => 3,
                'submitted_by'        => 9,
                'title_ar'            => 'تقرير مرحلة الـ Backend',
                'title_en'            => null,
                'content_ar'          => 'تم الانتهاء من تطوير الـ Controllers الرئيسية وربطها بقاعدة البيانات. تم اختبار جميع الـ APIs باستخدام Postman.',
                'content_en'          => null,
                'report_type'         => 'milestone',
                'week_number'         => 6,
                'report_date'         => '2025-03-28',
                'status'              => 'approved',
                'supervisor_feedback' => 'جيد جداً. يرجى التأكد من إضافة التحقق من الصلاحيات (Policies) لجميع العمليات.',
                'reviewed_by'         => 3,
                'reviewed_at'         => '2025-03-30 10:00:00',
                'grade'               => 90.0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'project_id'          => 3,
                'submitted_by'        => 9,
                'title_ar'            => 'تقرير الأسبوع العاشر - تطوير الواجهة',
                'title_en'            => null,
                'content_ar'          => 'جارٍ تطوير واجهة المستخدم. تم الانتهاء من 60% من الصفحات الرئيسية.',
                'content_en'          => null,
                'report_type'         => 'weekly',
                'week_number'         => 10,
                'report_date'         => '2025-04-21',
                'status'              => 'submitted',
                'supervisor_feedback' => null,
                'reviewed_by'         => null,
                'reviewed_at'         => null,
                'grade'               => null,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
        ]);
    }
}