<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectIdeaSeeder extends Seeder
{
    public function run(): void
    {
        $now  = now();
        $ideas = [

            // ── CS Department (dept=1) | Supervisor: Dr. Ahmed (user=3) ─────
            [
                'department_id'         => 1,
                'proposed_by'           => 3, // د. أحمد الغامدي
                'semester_id'           => 6, // الفصل الثاني 2024-2025
                'title_ar'              => 'نظام إدارة مشاريع التخرج الذكي',
                'title_en'              => 'Smart Graduation Project Management System',
                'description_ar'        => 'تطوير منصة إلكترونية متكاملة لإدارة مشاريع التخرج في الجامعات، تتيح للطلاب استعراض الأفكار واختيار المشاريع، وللمشرفين متابعة التقدم وتقديم الملاحظات، ولإدارة الكلية الإشراف الكامل على جميع المشاريع.',
                'description_en'        => 'A comprehensive web platform for managing university graduation projects, enabling students to browse ideas, supervisors to track progress, and administration to oversee all projects.',
                'objectives_ar'         => "تنظيم عملية إدارة مشاريع التخرج\nتسهيل التواصل بين الطلاب والمشرفين\nتوفير أرشيف رقمي للمشاريع السابقة\nتقليل الفوضى الإدارية والورقية",
                'expected_outcomes_ar'  => "منصة ويب متكاملة باللغتين العربية والإنجليزية\nنظام صلاحيات متعدد الأدوار\nتقارير وإحصاءات شاملة\nأرشيف قابل للبحث للمشاريع السابقة",
                'project_type'          => 'graduation',
                'category_ar'           => 'هندسة البرمجيات',
                'category_en'           => 'Software Engineering',
                'tags'                  => json_encode(['Laravel', 'Web', 'Management System']),
                'tools'                 => json_encode(['Laravel 11', 'MySQL', 'Bootstrap 5', 'JavaScript']),
                'technologies'          => json_encode(['PHP 8.3', 'Blade Templates', 'Eloquent ORM']),
                'requirements_ar'       => 'إتقان PHP وLaravel، معرفة بقواعد البيانات العلائقية، خبرة في HTML/CSS/JavaScript',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'high',
                'is_featured'           => true,
            ],

            [
                'department_id'         => 1,
                'proposed_by'           => 3,
                'semester_id'           => 6,
                'title_ar'              => 'تطبيق تتبع الحضور الجامعي باستخدام التعرف على الوجه',
                'title_en'              => 'University Attendance Tracking with Facial Recognition',
                'description_ar'        => 'نظام ذكي لتسجيل حضور الطلاب تلقائياً عن طريق التعرف على الوجه باستخدام كاميرات القاعات الدراسية وتقنيات الذكاء الاصطناعي.',
                'description_en'        => 'An intelligent system to automatically record student attendance through facial recognition using classroom cameras and AI.',
                'objectives_ar'         => "أتمتة تسجيل الحضور والغياب\nتقليل التلاعب والغش في الحضور\nتوفير تقارير فورية للمشرفين",
                'expected_outcomes_ar'  => "تطبيق ويب مع نظام التعرف على الوجه\nلوحة تحكم للمشرف مع تقارير\nتنبيهات فورية للغياب",
                'project_type'          => 'graduation',
                'category_ar'           => 'الذكاء الاصطناعي',
                'category_en'           => 'Artificial Intelligence',
                'tags'                  => json_encode(['AI', 'Facial Recognition', 'Computer Vision']),
                'tools'                 => json_encode(['Python', 'OpenCV', 'TensorFlow', 'Django', 'MySQL']),
                'technologies'          => json_encode(['Deep Learning', 'CNN', 'REST API']),
                'requirements_ar'       => 'إتقان Python، معرفة بأساسيات تعلم الآلة والتعلم العميق',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'high',
                'is_featured'           => true,
            ],

            // ── AI Department (dept=4) | Supervisor: Dr. Fatima (user=4) ───
            [
                'department_id'         => 4,
                'proposed_by'           => 4, // د. فاطمة الزهراني
                'semester_id'           => 6,
                'title_ar'              => 'نظام كشف الاحتيال في المعاملات البنكية باستخدام التعلم الآلي',
                'title_en'              => 'Bank Transaction Fraud Detection using Machine Learning',
                'description_ar'        => 'تطوير نموذج تعلم آلي للكشف عن المعاملات الاحتيالية في الوقت الفعلي مع واجهة مستخدم لعرض التنبيهات والتقارير.',
                'description_en'        => 'Developing a machine learning model to detect fraudulent transactions in real-time with a dashboard for alerts and reports.',
                'objectives_ar'         => "تدريب نموذج دقيق للكشف عن الاحتيال\nتحقيق دقة أعلى من 95%\nتوفير تفسيرات للقرارات",
                'expected_outcomes_ar'  => "نموذج ML مدرّب على بيانات حقيقية\nواجهة مستخدم لعرض النتائج\nتقارير الأداء والمقارنة",
                'project_type'          => 'graduation',
                'category_ar'           => 'تعلم الآلة',
                'category_en'           => 'Machine Learning',
                'tags'                  => json_encode(['ML', 'Fraud Detection', 'FinTech']),
                'tools'                 => json_encode(['Python', 'Scikit-learn', 'XGBoost', 'Pandas', 'Flask']),
                'technologies'          => json_encode(['Random Forest', 'Neural Networks', 'SMOTE']),
                'requirements_ar'       => 'إتقان Python وScikit-learn، فهم جيد لإحصاءات التعلم الآلي',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'high',
                'is_featured'           => false,
            ],

            [
                'department_id'         => 4,
                'proposed_by'           => 4,
                'semester_id'           => 6,
                'title_ar'              => 'روبوت محادثة ذكي للدعم الأكاديمي باللغة العربية',
                'title_en'              => 'Arabic AI Chatbot for Academic Support',
                'description_ar'        => 'بناء روبوت محادثة ذكي باللغة العربية يستجيب لاستفسارات الطلاب الأكاديمية ويساعدهم في الخطط الدراسية والجداول.',
                'description_en'        => 'Building an Arabic-language AI chatbot that responds to student academic inquiries and helps with study plans and schedules.',
                'objectives_ar'         => "دعم اللغة العربية بشكل احترافي\nالإجابة على الأسئلة الأكاديمية الشائعة\nالتكامل مع نظام الجامعة",
                'expected_outcomes_ar'  => "روبوت محادثة عربي وظيفي\nنظام RAG للمعرفة الأكاديمية\nواجهة ويب سهلة الاستخدام",
                'project_type'          => 'graduation',
                'category_ar'           => 'معالجة اللغات الطبيعية',
                'category_en'           => 'Natural Language Processing',
                'tags'                  => json_encode(['NLP', 'Arabic', 'Chatbot', 'LLM']),
                'tools'                 => json_encode(['Python', 'LangChain', 'OpenAI API', 'FastAPI', 'React']),
                'technologies'          => json_encode(['RAG', 'Vector Database', 'Arabic NLP']),
                'requirements_ar'       => 'خبرة في Python وبرمجة APIs، معرفة بأساسيات معالجة اللغات الطبيعية',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'medium',
                'is_featured'           => true,
            ],

            // ── IS Department (dept=2) | Supervisor: Dr. Khalid (user=5) ───
            [
                'department_id'         => 2,
                'proposed_by'           => 5, // د. خالد العتيبي
                'semester_id'           => 6,
                'title_ar'              => 'نظام إدارة المستشفيات الإلكتروني',
                'title_en'              => 'Electronic Hospital Management System',
                'description_ar'        => 'منصة شاملة لإدارة العمليات اليومية في المستشفيات تشمل تسجيل المرضى، جدولة المواعيد، إدارة الطواقم الطبية، والفواتير.',
                'description_en'        => 'A comprehensive platform for managing daily hospital operations including patient registration, appointment scheduling, medical staff management, and billing.',
                'objectives_ar'         => "رقمنة العمليات الإدارية للمستشفى\nتحسين تجربة المريض\nتوفير تقارير إدارية شاملة",
                'expected_outcomes_ar'  => "نظام ويب متكامل لإدارة المستشفى\nتطبيق موبايل للمرضى\nلوحة تحكم إدارية",
                'project_type'          => 'graduation',
                'category_ar'           => 'نظم المعلومات الصحية',
                'category_en'           => 'Health Information Systems',
                'tags'                  => json_encode(['Healthcare', 'Management System', 'Web']),
                'tools'                 => json_encode(['Laravel', 'Vue.js', 'MySQL', 'Pusher']),
                'technologies'          => json_encode(['REST API', 'WebSockets', 'PDF Generation']),
                'requirements_ar'       => 'إتقان Laravel أو أطر عمل مشابهة، فهم قواعد البيانات المعقدة',
                'min_students'          => 3,
                'max_students'          => 4,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'high',
                'is_featured'           => false,
            ],

            [
                'department_id'         => 2,
                'proposed_by'           => 5,
                'semester_id'           => 6,
                'title_ar'              => 'منصة تعليم إلكتروني تفاعلية (LMS)',
                'title_en'              => 'Interactive E-Learning Platform (LMS)',
                'description_ar'        => 'بناء منصة تعليمية إلكترونية تدعم المحاضرات المباشرة والمسجلة، الاختبارات التفاعلية، تتبع تقدم الطالب، ومنتديات النقاش.',
                'description_en'        => 'Building an e-learning platform supporting live and recorded lectures, interactive quizzes, student progress tracking, and discussion forums.',
                'objectives_ar'         => "توفير بيئة تعليمية رقمية متكاملة\nدعم التعلم المتزامن وغير المتزامن\nتقديم تحليلات تعليمية للمعلمين",
                'expected_outcomes_ar'  => "منصة ويب LMS وظيفية\nنظام الاختبارات والتقييم\nتقارير تقدم الطلاب",
                'project_type'          => 'graduation',
                'category_ar'           => 'التعليم الإلكتروني',
                'category_en'           => 'E-Learning',
                'tags'                  => json_encode(['LMS', 'Education', 'Web Platform']),
                'tools'                 => json_encode(['Laravel', 'React', 'MySQL', 'WebRTC', 'Redis']),
                'technologies'          => json_encode(['Real-time Communication', 'Video Streaming', 'Progressive Web App']),
                'requirements_ar'       => 'خبرة في تطوير الويب المتقدم، معرفة بتقنيات البث المباشر',
                'min_students'          => 3,
                'max_students'          => 4,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'medium',
                'is_featured'           => false,
            ],

            // ── IT Department (dept=3) | Supervisor: Dr. Mona (user=6) ────
            [
                'department_id'         => 3,
                'proposed_by'           => 6, // د. منى الشهري
                'semester_id'           => 6,
                'title_ar'              => 'نظام مراقبة أمن الشبكات بالوقت الفعلي',
                'title_en'              => 'Real-time Network Security Monitoring System',
                'description_ar'        => 'تطوير نظام لمراقبة حركة مرور الشبكة واكتشاف التهديدات الأمنية في الوقت الفعلي مع إصدار تنبيهات فورية للمسؤولين.',
                'description_en'        => 'Developing a system to monitor network traffic and detect security threats in real-time with instant alerts for administrators.',
                'objectives_ar'         => "مراقبة حركة الشبكة بشكل مستمر\nاكتشاف الشذوذات والتهديدات\nتوليد تقارير أمنية تفصيلية",
                'expected_outcomes_ar'  => "داشبورد مراقبة أمني في الوقت الفعلي\nنظام تنبيهات متعدد القنوات\nتقارير أمنية يومية وأسبوعية",
                'project_type'          => 'graduation',
                'category_ar'           => 'أمن المعلومات',
                'category_en'           => 'Information Security',
                'tags'                  => json_encode(['Security', 'Network', 'Real-time', 'IDS']),
                'tools'                 => json_encode(['Python', 'Elasticsearch', 'Kibana', 'Snort', 'Django']),
                'technologies'          => json_encode(['SIEM', 'Packet Analysis', 'Machine Learning Anomaly Detection']),
                'requirements_ar'       => 'إتقان Python وأساسيات أمن الشبكات، معرفة بـ Linux وأدوات مراقبة الشبكة',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'high',
                'is_featured'           => false,
            ],

            // ── Pending Idea (not yet approved) ───────────────────────────
            [
                'department_id'         => 1,
                'proposed_by'           => 3,
                'semester_id'           => 6,
                'title_ar'              => 'تطبيق إدارة العقارات الذكي',
                'title_en'              => 'Smart Real Estate Management App',
                'description_ar'        => 'تطبيق متكامل لإدارة العقارات يدعم إدراج العقارات، إدارة العقود، المدفوعات، وتقارير الأرباح.',
                'description_en'        => 'A comprehensive real estate management app supporting property listings, contract management, payments, and profit reports.',
                'objectives_ar'         => "رقمنة عمليات إدارة العقارات\nتبسيط عمليات التأجير والبيع",
                'expected_outcomes_ar'  => "تطبيق ويب وموبايل\nنظام إدارة العقود الإلكتروني",
                'project_type'          => 'graduation',
                'category_ar'           => 'تطوير التطبيقات',
                'category_en'           => 'Application Development',
                'tags'                  => json_encode(['Real Estate', 'Web App', 'Mobile']),
                'tools'                 => json_encode(['Laravel', 'Flutter', 'MySQL']),
                'technologies'          => json_encode(['REST API', 'Cross-Platform']),
                'requirements_ar'       => 'خبرة في تطوير تطبيقات الويب والموبايل',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'pending',
                'approved_by'           => null,
                'approved_at'           => null,
                'priority'              => 'medium',
                'is_featured'           => false,
            ],

            // ── Semester Project (فصلي) ──────────────────────────────────
            [
                'department_id'         => 2,
                'proposed_by'           => 5,
                'semester_id'           => 6,
                'title_ar'              => 'نظام حجز مواعيد المرافق الجامعية',
                'title_en'              => 'University Facilities Booking System',
                'description_ar'        => 'نظام لحجز القاعات والملاعب والمعامل في الجامعة مع التحقق من التوافر والمنع من التضارب.',
                'description_en'        => 'A system for booking halls, courts, and labs in the university with availability verification and conflict prevention.',
                'objectives_ar'         => "تسهيل حجز المرافق الجامعية\nمنع تضارب الحجوزات\nتوفير تقارير الاستخدام",
                'expected_outcomes_ar'  => "تطبيق ويب للحجز\nتقويم تفاعلي للمواعيد\nنظام تأكيد بالبريد الإلكتروني",
                'project_type'          => 'semester',
                'category_ar'           => 'تطوير الويب',
                'category_en'           => 'Web Development',
                'tags'                  => json_encode(['Booking System', 'University', 'Web']),
                'tools'                 => json_encode(['Laravel', 'FullCalendar.js', 'MySQL', 'Bootstrap']),
                'technologies'          => json_encode(['REST API', 'Email Notifications', 'AJAX']),
                'requirements_ar'       => 'معرفة بـ Laravel وJavaScript والتقويمات التفاعلية',
                'min_students'          => 2,
                'max_students'          => 3,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'medium',
                'is_featured'           => false,
            ],

            // ── Year 4 Project ───────────────────────────────────────────
            [
                'department_id'         => 4,
                'proposed_by'           => 4,
                'semester_id'           => 5,
                'title_ar'              => 'نموذج توليد النصوص العربية باستخدام الشبكات العصبية',
                'title_en'              => 'Arabic Text Generation Model using Neural Networks',
                'description_ar'        => 'بناء نموذج توليد نصوص عربية باستخدام شبكات LSTM أو Transformer مع قاعدة بيانات واسعة من النصوص العربية.',
                'description_en'        => 'Building an Arabic text generation model using LSTM or Transformer networks with a large Arabic text corpus.',
                'objectives_ar'         => "توليد نصوص عربية سليمة نحوياً\nدعم مجالات متعددة\nقياس جودة النصوص المولّدة",
                'expected_outcomes_ar'  => "نموذج NLP عربي مدرّب\nواجهة لتوليد النصوص\nورقة بحثية عن النتائج",
                'project_type'          => 'year4',
                'category_ar'           => 'معالجة اللغات الطبيعية',
                'category_en'           => 'NLP',
                'tags'                  => json_encode(['Arabic NLP', 'Text Generation', 'Deep Learning']),
                'tools'                 => json_encode(['Python', 'PyTorch', 'HuggingFace', 'Jupyter']),
                'technologies'          => json_encode(['Transformer', 'BERT Arabic', 'GPT-style models']),
                'requirements_ar'       => 'خلفية قوية في تعلم الآلة والشبكات العصبية',
                'min_students'          => 1,
                'max_students'          => 2,
                'status'                => 'approved',
                'approved_by'           => 1,
                'approved_at'           => $now,
                'priority'              => 'high',
                'is_featured'           => false,
            ],
        ];

        foreach ($ideas as $idea) {
            DB::table('project_ideas')->insert(array_merge($idea, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}