<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            // ── Admin ──────────────────────────────────────────────────────
            [
                'university_id'    => 1,
                'college_id'       => 1,
                'department_id'    => 1,
                'name_ar'          => 'مدير النظام',
                'name_en'          => 'System Admin',
                'email'            => 'admin@kau.edu.sa',
                'employee_id'      => 'EMP-0001',
                'role'             => 'admin',
                'academic_rank'    => null,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],

            // ── Coordinator ────────────────────────────────────────────────
            [
                'university_id'    => 1,
                'college_id'       => 1,
                'department_id'    => 1,
                'name_ar'          => 'أ. سارة المنسقة',
                'name_en'          => 'Sarah Coordinator',
                'email'            => 'coordinator@kau.edu.sa',
                'employee_id'      => 'EMP-0002',
                'role'             => 'coordinator',
                'academic_rank'    => 'منسقة',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],

            // ── Supervisors ────────────────────────────────────────────────
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 1,
                'name_ar'          => 'د. أحمد الغامدي',
                'name_en'          => 'Dr. Ahmed Al-Ghamdi',
                'email'            => 'ahmed.ghamdi@kau.edu.sa',
                'employee_id'      => 'EMP-0010',
                'role'             => 'supervisor',
                'academic_rank'    => 'أستاذ مشارك',
                'specialization_ar'=> 'هندسة البرمجيات والأنظمة الموزعة',
                'specialization_en'=> 'Software Engineering & Distributed Systems',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'dark',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 4,
                'name_ar'          => 'د. فاطمة الزهراني',
                'name_en'          => 'Dr. Fatima Al-Zahrani',
                'email'            => 'fatima.zahrani@kau.edu.sa',
                'employee_id'      => 'EMP-0011',
                'role'             => 'supervisor',
                'academic_rank'    => 'أستاذ مساعد',
                'specialization_ar'=> 'الذكاء الاصطناعي وتعلم الآلة',
                'specialization_en'=> 'Artificial Intelligence & Machine Learning',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 2,
                'name_ar'          => 'د. خالد العتيبي',
                'name_en'          => 'Dr. Khalid Al-Otaibi',
                'email'            => 'khalid.otaibi@kau.edu.sa',
                'employee_id'      => 'EMP-0012',
                'role'             => 'supervisor',
                'academic_rank'    => 'أستاذ',
                'specialization_ar'=> 'قواعد البيانات ونظم المعلومات',
                'specialization_en'=> 'Databases & Information Systems',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 3,
                'name_ar'          => 'د. منى الشهري',
                'name_en'          => 'Dr. Mona Al-Shahri',
                'email'            => 'mona.shahri@kau.edu.sa',
                'employee_id'      => 'EMP-0013',
                'role'             => 'supervisor',
                'academic_rank'    => 'أستاذ مساعد',
                'specialization_ar'=> 'أمن المعلومات والشبكات',
                'specialization_en'=> 'Information Security & Networks',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],

            // ── Committee Members ──────────────────────────────────────────
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 1,
                'name_ar'          => 'أ.د. عبدالله القحطاني',
                'name_en'          => 'Prof. Abdullah Al-Qahtani',
                'email'            => 'qahtani@kau.edu.sa',
                'employee_id'      => 'EMP-0020',
                'role'             => 'committee_member',
                'academic_rank'    => 'أستاذ',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 2,
                'name_ar'          => 'د. ريم السلمي',
                'name_en'          => 'Dr. Reem Al-Salmi',
                'email'            => 'reem.salmi@kau.edu.sa',
                'employee_id'      => 'EMP-0021',
                'role'             => 'committee_member',
                'academic_rank'    => 'أستاذ مشارك',
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'dark',
                'password'         => Hash::make('password'),
            ],

            // ── Students ───────────────────────────────────────────────────
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 1,
                'name_ar'          => 'محمد علي الحربي',
                'name_en'          => 'Mohammed Ali Al-Harbi',
                'email'            => 's.mohammed@kau.edu.sa',
                'student_id'       => '2020001001',
                'role'             => 'student',
                'academic_year'    => 4,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 1,
                'name_ar'          => 'سلمى خالد الجهني',
                'name_en'          => 'Salma Khalid Al-Johani',
                'email'            => 's.salma@kau.edu.sa',
                'student_id'       => '2020001002',
                'role'             => 'student',
                'academic_year'    => 4,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 1,
                'name_ar'          => 'عبدالرحمن سعد الدوسري',
                'name_en'          => 'Abdulrahman Saad Al-Dosari',
                'email'            => 's.abdulrahman@kau.edu.sa',
                'student_id'       => '2020001003',
                'role'             => 'student',
                'academic_year'    => 4,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'dark',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 4,
                'name_ar'          => 'نورة عبدالله الشمري',
                'name_en'          => 'Noura Abdullah Al-Shammari',
                'email'            => 's.noura@kau.edu.sa',
                'student_id'       => '2020004001',
                'role'             => 'student',
                'academic_year'    => 4,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 4,
                'name_ar'          => 'فهد يوسف الرشيدي',
                'name_en'          => 'Fahad Yousef Al-Rashidi',
                'email'            => 's.fahad@kau.edu.sa',
                'student_id'       => '2020004002',
                'role'             => 'student',
                'academic_year'    => 4,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 2,
                'name_ar'          => 'ليلى عمر المطيري',
                'name_en'          => 'Layla Omar Al-Mutairi',
                'email'            => 's.layla@kau.edu.sa',
                'student_id'       => '2021002001',
                'role'             => 'student',
                'academic_year'    => 3,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
            [
                'university_id'    => 1, 'college_id' => 1, 'department_id' => 2,
                'name_ar'          => 'عمر طارق السبيعي',
                'name_en'          => 'Omar Tariq Al-Subaie',
                'email'            => 's.omar@kau.edu.sa',
                'student_id'       => '2021002002',
                'role'             => 'student',
                'academic_year'    => 3,
                'status'           => 'active',
                'lang_preference'  => 'ar',
                'theme_preference' => 'light',
                'password'         => Hash::make('password'),
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert(array_merge($user, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}